/* --------------------------------------------------------------------
 * DO NOT EDIT THIS FILE!  It has been automatically generated
 * by configure on host: max
 * --------------------------------------------------------------------
 */
#ifndef IMS_MATH_H
#define IMS_MATH_H

#include <math.h>

#endif
