/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* "configure arguments" */
#define CONFIGURE_ARGS "'--host=i586-mingw32msvc' '--build=x86_64-linux' '--enable-static' '--disable-shared' 'build_alias=x86_64-linux' 'host_alias=i586-mingw32msvc'"

/* Debug */
/* #undef DEBUG */

/* Define to 1 if you have the <dlfcn.h> header file. */
/* #undef HAVE_DLFCN_H */

/* C99 function */
#define HAVE_FLOOR 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* C99 function */
#define HAVE_ROUND 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* No Debug */
#define NDEBUG 1

/* Name of package */
#define PACKAGE "imslib"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "apervukh@minet.uni-jena.de"

/* Define to the full name of this package. */
#define PACKAGE_NAME "ims library"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "ims library 0.5.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "imslib"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.5.0"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.5.0"
