/* --------------------------------------------------------------------
 * DO NOT EDIT THIS FILE!  It has been automatically generated.
 * --------------------------------------------------------------------
 */
#ifndef IMS_MATH_H
#define IMS_MATH_H

#include <math.h>

@ROUND_FUNCTION@

#endif
